### ISSUE TITLE
Wrong path for My Drive

### ISSUE THREAD

**Issue by mzakstudio** [TheCaduceus/Torrent-to-GoogleDrive#1]
Default path for My Drive Download is wrong. It should be {"save_path": "/gdrive/My Drive/Torrent"}

**Comment by TheCaduceus** [comment]
> Default path for My Drive Download is wrong. It should be {"save_path": "/gdrive/My Drive/Torrent"}

Thanks for Reporting this Error! Successfully fixed it. ☺️
