### ISSUE TITLE
why is it filling up my colab's disk space

### ISSUE THREAD

**Issue by mikebilly** [TheCaduceus/Torrent-to-GoogleDrive#2]
I have 300+ gb free on my google drive account, but only around 40 gb of disk space on colab. I can't download a 200gb torrent file to google drive because it keeps filling up my colab's 40gb free disk space instead of my drive. Seems like it downloads to colab's disk first, then copies to drive. Is there a way to make it download directly to my drive without filling up any disk space on colab?

**Comment by TheCaduceus** [comment]
@mikebilly Colab already provides option to connect your VPS/PC or Google Cloud Machine to extend your resource limits.

**Comment by mikebilly** [comment]
@TheCaduceus is it free? I just want it to download to my drive without using any other disk space, or otherwise if it's free then could you tell me how to?
